hyper-deploy-steps: &hyper-deploy-steps
  - attach_workspace:
      at: ~/circleci-deployment
  - checkout
  - run:
      name: install docker-compose
      command: |
        curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
  - run:  chmod +x ~/docker-compose
  - run:  sudo mv ~/docker-compose /usr/local/bin/docker-compose
  - setup_remote_docker
  - run:
      name: Build Docker
      command: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker build -f dockerbuild/Dockerfile -t bespoken/encoder:$CIRCLE_TAG .
        docker push bespoken/encoder:$CIRCLE_TAG
  - run:
      name: Deploy container
      command: |
        sudo npm install fargate-helper -g
        fargate service \
        --command "node outputs/source/lib/index.js" \
        --containerPort 3000 \
        --cpu 256 \
        --memory 512 \
        --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        --env AWS_DEFAULT_REGION=$AWS_REGION \
        --image bespoken/encoder:$CIRCLE_TAG \
        --name encoder

version: 2
jobs:
  test:
    docker:
      # This is a custom image in ubuntu that includes node 6 and ffmpeg in order to run the test , Dockerbuild is
      # in dockerbuild/testContainer/Dockerfile
      - image: jperata/encodertest:1
    working_directory: ~/circleci-deployment
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test
      - persist_to_workspace:
          root: .
          paths: .

  encoder-prod:
    docker:
          - image: circleci/node
    working_directory: ~/circleci-deployment
    steps: *hyper-deploy-steps


workflows:
  version: 2
  test-n-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - encoder-prod:
          requires:
            - test
          filters:
            tags:
              only: /encoder-prod-.*/
            branches:
              ignore: /.*/
