encoder-master:
  image: bespoken/bespoken-encoder:${CIRCLE_BUILD_NUM}
  stdin_open: true
  tty: true
  ports:
  - 80:5900/tcp
  environment:
    AWS_KEY: ${AWS_KEY}
    AWS_SECRET: ${AWS_SECRET}
  labels:
    io.rancher.container.pull_image: always